---

- name: application input splitting to list
  set_fact:
    app_cache: "{{ dest_applications.split('\n') }}"
  when: survey

- name: match applications to junos format
  set_fact:
    applications: "{{ applications + [__appmatch[item]] }}"
  loop: "{{ app_cache }}"

- name: apps
  debug:
    msg: "{{ applications }}"
  tags: debug