---
# tasks file for firewall

- name: set fw provider
  set_fact: 
   __backup_manager_provider: "{{ __backup_manager_provider | 
        combine( { 'username': panos_username, 
        'password': panos_password, 'ip_address': ansible_host }) }}"

- include_tasks: application_mapping.yml
  when: survey

- include_vars: policy.yml
  when: survey

- debug: 
    msg: "{{ fw_rule_src_zone }}" 

- name: include address object
  include_tasks: address_object.yml

- name: include rules
  include_tasks: rule.yml
