---

- name: set fw provider
  set_fact: 
   __backup_manager_provider: "{{ __backup_manager_provider | 
        combine( { 'username': panos_username, 
        'password': panos_password, 'ip_address': ansible_host }) }}"

- name: debug provider
  debug:
    msg: "{{ __backup_manager_provider }}"

- debug: msg="{{ lookup('env','PANOS_PASSWORD') }}"

- name: debug hostvars
  debug:
    msg: "{{ hostvars }}"

- name: add rule to firewall
  panos_security_rule:
    provider: "{{ __backup_manager_provider }}"
    rule_name: "{{ fw_rule_name }}"
    description: "{{ fw_rule_description }}"
    source_zone: ["{{ fw_rule_src_zone }}"]
    destination_zone: ["{{ fw_rule_dest_zone }}"]
    source_ip: ["{{ fw_rule_src_ip }}"]
    source_user: ['any']
    destination_ip: ["{{ fw_rule_dest_ip }}"]
    category: ['any']
    application: ['any']
    service: "{{ fw_rule_service }}"
    hip_profiles: ['any']
    state: "{{ fw_rule_state }}"
    action: "{{ fw_rule_action }}"
    commit: 'False'
    #    tag_name: "{{ fw_rule_tag }}"
