---

- name: add rule to firewall
  panos_security_rule:
    provider: "{{ __backup_manager_provider }}"
    rule_name: "{{ ansible_host }} - {{ name }}"
    description: "{{ fw_rule_description | default(omit) }}"
    source_zone: ["{{ fw_rule_src_zone }}"]
    destination_zone: ["{{ fw_rule_dest_zone }}"]
    source_ip: ["{{ fw_rule_src_ip }}"]
    source_user: ['any']
    destination_ip: ["{{ item.ip_address }}"]
    category: ['any']
    application: ['any']
    service: "{{ fw_rule_service }}"
    hip_profiles: ['any']
    state: "{{ fw_rule_state }}"
    action: "{{ item.action }}"
    commit: 'False'
  loop: "{{ fw_rule_destinations }}"
    #    tag_name: "{{ fw_rule_tag }}"