---

- name: debug hostvars
  debug:
    msg: "{{ hostvars }}"

- name: set fw provider
  set_fact: 
    fw_provider: "{{ fw_provider | combine( { 'username': fw_username, 
      'password': fw_password, 'ip_address': fw_ip_address }) }}"

- name: add rule to firewall
  panos_security_rule:
    provider: "{{ fw_provider }}" 
    rule_name: "{{ fw_rule_name }}"
    description: "{{ fw_rule_description }}"
    source_zone: ["{{ fw_rule_src_zone }}"]
    destination_zone: ["{{ fw_rule_dest_zone }}"]
    source_ip: ["{{ fw_rule_src_ip }}"]
    source_user: ['any']
    destination_ip: ["{{ fw_rule_dest_ip }}"]
    category: ['any']
    application: ['any']
    service: "{{ fw_rule_service }}"
    hip_profiles: ['any']
    state: "{{ fw_rule_state }}"
    action: "{{ fw_rule_action }}"
    commit: 'False'
    #    tag_name: "{{ fw_rule_tag }}"
