
fw_rule_name: "{{ src_hostname }}_{{ dest_hostname }}"
fw_rule_description: "ansible created rule {{ src_hostname }} to {{ dest_hostname }}"
fw_rule_src_zone: "{{ src_zone }}"
fw_rule_dest_zone: "{{ dest_zone }}"
fw_rule_src_ip: "{{ src_ip_address }}"
fw_rule_dest_ip: "{{ dest_ip_address }}"
fw_rule_dest_hostname: "{{ dest_hostname }}"
fw_rule_src_hostname: "{{ src_hostname }}"
fw_rule_service: 
  - service-https
  - service-http
fw_rule_tag: tag
fw_rule_action: "{% if fw_action == 'permit' %}allow{% else %}deny{% endif %}"